# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
ENABLE:
  - TYPESCRIPT
  - JAVASCRIPT
  - RUST
  - GO
  - PYTHON
  - DOCKERFILE

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  # - REPOSITORY_GITLEAKS
  - REPOSITORY_TRUFFLEHOG
  # - DOCKERFILE_HADOLINT
  # - BASH_SHELLCHECK
  # - API_SPECTRAL

# DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

## project is the default
REPOSITORY_TRIVY_CLI_LINT_MODE: project
