name: 01-set-tag

on:
  workflow_dispatch:
    inputs:        
      proposed-release-tag:
        type: string
        description: 'Tag version to use (i.e. v1.2.3)'
        required: false

jobs:

  set-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Tag
        id: gettag
        if: ${{ github.event.inputs.proposed-release-tag }}
        run: |
          PROPOSED_TAG=$(echo '${{ github.event.inputs.proposed-release-tag }}' | sed 's/\s//g' | sed 's/^\(v\|V\)*\(.*\)/v\2/g')
          echo "PROPOSED_TAG: $PROPOSED_TAG"
          echo "my_version=$PROPOSED_TAG" >> $GITHUB_OUTPUT
          #git tag -a $PROPOSED_TAG -m "Tagged from Github workflow"

      - name: Set Github Tag via API
        uses: actions/github-script@v6
        with:
          #github-token: ${{ secrets.ARABOT_PAT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.gettag.outputs.my_version }}-test`,
              sha: "${{ github.sha }}"
            })
        