name: 01-set-tag

on:
  workflow_dispatch:
    inputs:        
      proposed-release-tag:
        type: string
        description: 'Tag version to use (i.e. v1.2.3)'
        required: true

jobs:

  set-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.PAT_TEST_API }}

      - name: Get Tag
        id: gettag
        if: ${{ github.event.inputs.proposed-release-tag }}
        run: |
          PROPOSED_TAG=$(echo '${{ github.event.inputs.proposed-release-tag }}' | sed 's/\s//g' | sed 's/^\(v\|V\)*\(.*\)/v\2/g')
          echo "PROPOSED_TAG: $PROPOSED_TAG"
          echo "VERSION=$PROPOSED_TAG" >> $GITHUB_OUTPUT

      - name: Set Github Tag via API
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TEST_API }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.gettag.outputs.VERSION }}-test`,
              sha: "${{ github.sha }}"
            })
        