name: spectral-ci

on:
  push:
    branches: [api]
  pull_request:
    types:
      - opened
    branches: [api]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  spectral_cli:
    name: Spectral CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Spectral
        run: |
          npm install @stoplight/spectral-cli
          npm install @stoplight/spectral-owasp-ruleset

      - name: Setup Spectral rulesets
        run: |
          echo 'extends: ["spectral:oas"]' > .spectral_oas.yaml   # ruleset was already installed when the linter was installed
          echo 'extends: ["@stoplight/spectral-owasp-ruleset"]' > .spectral_owasp.yaml    # ruleset had to be installed before with npm install
          echo 'extends: ["https://unpkg.com/@apisyouwonthate/style-guide@1.3.2/dist/ruleset.js"]' > .spectral_style_guide.yaml   # ruleset is downloaded in runtime

      - name: Run Spectral
        run: |
          mkdir -p _out/
          set -o pipefail; npx spectral lint src/api_specs/openapi01.yaml -r .spectral_oas.yaml -v | tee _out/spectral_oas.log
          set -o pipefail; npx spectral lint src/api_specs/openapi01.yaml -r .spectral_owasp.yaml -v | tee _out/spectral_owasp.log
          set -o pipefail; npx spectral lint src/api_specs/openapi01.yaml -r .spectral_style_guide.yaml -v | tee _out/spectral_style_guide.log
          set +o pipefail

      - name: Archive Spectral reports
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Spectral reports
          path: _out/*.log

  # spectral_action:
  #   name: Spectral GH Action
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Download and setup Spectral Rulesets
  #       run: |
  #         echo 'extends: ["spectral:oas", "https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.2.0/dist/ruleset.js"]' > .spectral.yaml

  #     - name: Run Spectral Actions
  #       uses: stoplightio/spectral-action@latest
  #       with:
  #         file_glob: './src/api_specs/**/*.oas*.{json,yml,yaml}'