name: spectral-ci

on:
  push:
    branches: [api]
  pull_request:
    types:
      - opened
    branches: [api]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  spectral_cli:
    name: Setup and run Spectral CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Download and setup Spectral Rulesets
        run: |
          npm install -g @stoplight/spectral-cli
          npm install --save -D @stoplight/spectral-owasp-ruleset
          #npm install --save -D @stoplight/spectral-cli
          echo 'extends: ["spectral:oas", "@stoplight/spectral-owasp-ruleset"]' > .spectral.yaml

      - name: Run Spectral CLI
        run: spectral lint ./src/api_specs/**/*.oas*.{json,yml,yaml} --output spectral_out.log

      - name: Archive Spectral reports
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: |
            spectral_out.log

      - name: Explore workdir and echo vars
        if: ${{ success() }} || ${{ failure() }}
        run: |
          ls -la
          echo home_path: $(pwd)
          cat .spectral.yaml
          ls -la node_modules/@stoplight/spectral-owasp-ruleset/

  spectral_action:
    name: Setup and run Github Spectral Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download and setup Spectral Rulesets
        run: |
          echo 'extends: ["spectral:oas", "@stoplight/spectral-owasp-ruleset"]' > .spectral.yaml

      - name: Run Spectral Actions
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: './src/api_specs/**/*.oas*.{json,yml,yaml}'