name: spectral-ci

on:
  push:
    branches: [api]
  pull_request:
    types:
      - opened
    branches: [api]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  spectral_cli:
    name: Spectral CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Download and setup Spectral Rulesets
        run: |
          npm install -g @stoplight/spectral-cli
          #npm install --save -D @stoplight/spectral-owasp-ruleset
          #npm install --save -D @stoplight/spectral-cli
          #echo 'extends: ["spectral:oas", "@stoplight/spectral-owasp-ruleset"]' > .spectral.yaml
          #echo 'extends: ["spectral:oas", "https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.2.0/dist/ruleset.js"]' > .spectral.yaml
          echo 'extends: ["spectral:oas"]' > .spectral.yaml

      - name: Run Spectral CLI
        #run: spectral lint ./src/api_specs/**/*.oas*.{json,yml,yaml} -r https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.2.0/dist/ruleset.js
        run: spectral lint ./src/api_specs/openapi01.yaml -r https://unpkg.com/@apisyouwonthate/style-guide@1.3.2/dist/ruleset.js -o spectral_out -f["html","stylish,"junit"] -v

      - name: Archive Spectral reports
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: |
            spectral_out.*

      - name: Explore workdir and echo vars
        if: ${{ success() }} || ${{ failure() }}
        run: |
          ls -la
          echo home_path: $(pwd)
          cat .spectral.yaml
          #ls -la node_modules/@stoplight/spectral-owasp-ruleset/

  # spectral_action:
  #   name: Spectral GH Action
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Download and setup Spectral Rulesets
  #       run: |
  #         echo 'extends: ["spectral:oas", "https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.2.0/dist/ruleset.js"]' > .spectral.yaml

  #     - name: Run Spectral Actions
  #       uses: stoplightio/spectral-action@latest
  #       with:
  #         file_glob: './src/api_specs/**/*.oas*.{json,yml,yaml}'