name: spectral-ci

on:
  push:
    branches: [api]
  pull_request:
    types:
      - opened
    branches: [api]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  spectral_cli:
    name: Spectral CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Spectral
        run: |
          npm install @stoplight/spectral-cli
          npm install @stoplight/spectral-owasp-ruleset

      - name: Setup Spectral rulesets
        run: |
          echo 'extends: ["spectral:oas"]' > .spectral.oas.yaml   # ruleset was already installed when the linter was installed
          echo 'extends: ["spectral:oas", "@stoplight/spectral-owasp-ruleset"]' > .spectral.oas_owasp.yaml  # ruleset had to be installed before (npm install xyz)
          echo 'extends: ["https://unpkg.com/@apisyouwonthate/style-guide@1.3.2/dist/ruleset.js"]' > .spectral.style_guide.yaml   # ruleset is downloaded in runtime

      - name: Run Spectral
        run: |
          mkdir -p _out/
          npx spectral lint ./src/api_specs/openapi01.yaml -r .spectral.oas.yaml -v > _out/spectral.oas.log
          npx spectral lint ./src/api_specs/openapi01.yaml -r .spectral.oas_owasp.yaml -v > _out/spectral.oas_owasp.log
          npx spectral lint ./src/api_specs/openapi01.yaml -r .spectral.style_guide.yaml -v > _out/spectral.style_guide.log

      - name: Archive Spectral reports
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Spectral reports
          path: _out/*.log

  # spectral_action:
  #   name: Spectral GH Action
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Download and setup Spectral Rulesets
  #       run: |
  #         echo 'extends: ["spectral:oas", "https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.2.0/dist/ruleset.js"]' > .spectral.yaml

  #     - name: Run Spectral Actions
  #       uses: stoplightio/spectral-action@latest
  #       with:
  #         file_glob: './src/api_specs/**/*.oas*.{json,yml,yaml}'